accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.loginViews, name='login'),
    path('register', views.registerViews, name='register'),
    path('forgot', views.forgotViews, name='forgot'),
    path('logout/', views.logoutUser, name='logout')
]

ar/urls.py
from django.urls import path
from . import views
app_name = "ar"

urlpatterns = [
    path('', views.homeviews, name='home')
]

assistant/urls.py
from django.contrib import admin
from django.urls import include,path


# static and media
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('accounts.urls')),
    path('ar', include('ar.urls')),
    path('chatbot/', include('chatbot.urls')),
    path('assistant/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatbot/urls.py
from django.urls import path
from . import views

app_name = "chatbot"

urlpatterns = [
    path("chatbot", views.chatapp, name='home'),
    path("", views.landPage, name='landing')
]

accounts/models.py
from django.db import models

# Create your models here.

ar/models.py
from django.db import models

# Create your models here.

chatbot/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
    
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'form-control', 'placeholder':'Username','style':'background-color: rgb(211, 241, 147);border-radius: 10px'})
        self.fields['email'].widget.attrs.update({'class':'form-control', 'placeholder':'Email','style':'background-color: rgb(211, 241, 147); border-radius: 10px','required':'True'})
        self.fields['password1'].widget.attrs.update({'class':'form-control', 'placeholder':'Password','style':'background-color: rgb(211, 241, 147); border-radius: 10px'})
        self.fields['password2'].widget.attrs.update({'class':'form-control', 'placeholder':'Confirm Password','style':'background-color: rgb(211, 241, 147); border-radius: 10px'})

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib import messages
# Create your views here.

def loginViews(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request,user)
            return redirect("chatbot:landing")
        else:
            messages.error(request, 'Oops, Invalid Username or Password.try again')

    return render(request, 'accounts/login.html')


def registerViews(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            # login in user direct on registration
            user = authenticate(
                request, username=user.username, password=request.POST['password1']
            )

            if user is not None:
                login(request, user)
                return redirect('chatbot:home')
            else:
                messages.error(request, 'Oops, something went wrong! try again later')

    context = {'form':form}
    return render(request, 'accounts/register.html', context)


def forgotViews(request):
    return render(request, 'accounts/forgot.html')


def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

ar/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='accounts:login')
def homeviews(request):
    return render(request, "ar/index.html")

chatbot/views.py
from django.shortcuts import render
from django.http import JsonResponse
import openai
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from dotenv import load_dotenv
import os

def configure():
    load_dotenv()

openai_api_key ='os.getenv()'
openai_api_key=configure()

#Function that sends a request to openai api with our message
# and then get a response from api
def ask_openai(message):
    response=openai.ChatCompletion.create(
        model = "gpt-3.5-turbo",
       messages=[
                {"role": "system","content": "You are a helpful assistant to the Makerere University Community. Your name is LAKY"},
                {"role": "user", "content": message},
       ],
       
        max_tokens=150,
        n=1,
        stop=None,
        temperature=0.7,
        
    )
   
    answer= response['choices'][0]['message']['content']
    return(answer)
@login_required(login_url='accounts:login')
def chatapp(request):
    if request.method == 'POST':
        message = request.POST.get('message')
        response =ask_openai(message)
        return JsonResponse({'message': message,'response': response})
    return render(request, 'chatbot/chat.html')


@login_required(login_url='accounts:login')
def landPage(request):
    
    return render(request, 'chatbot/index.html')

accounts/templates/accounts/forgot.html
{% extends "main.html" %}
{% load static %}

<title>
    {% block title %}
    Forgot password
    {% endblock title %}
</title>

{% block content %}
<main>
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <div class="card mb-3">

            <div class="card-body">

              <div class="icon">
                <a href="/"><i class="bx bx-arrow-back" style="font-size: 40px;"></i></a>
              </div>

              <div class="container">

                <div class="pt-4">
                  <h6 class="card-title text-center pb-0 fs-4">MUK ASSISTANT</h6>
                </div>

                <div class="d-flex justify-content-center py-4">
                  <a href="" class="d-flex align-items-center w-auto">
                    <img style="height: 100px;" src="{% static 'assets/img/go.png' %}" alt="">
                  </a>
                </div>

                <div class="pb-2">
                  <h6 class="card-title text-center pb-0 fs-4">Enter Register Email</h6>
                </div>

                <form class="row g-3 needs-validation" novalidate>

                  <div class="col-12 pt-4">
                    <div class="input-group has-validation">
                      <input type="email" name="username" style="background-color: rgb(211, 241, 147);" placeholder="Email" class="form-control" id="yourUsername" required>
                      <div class="invalid-feedback">Please enter your Registered Email.</div>
                    </div>
                  </div>

                  <div class="col-12 py-5">
                    <button class="btn w-100" style="background-color: rgb(241, 245, 241); color: blue;" type="submit">Verify Your Email</button>
                  </div>                 
                </form>
              </div>
            </div>

            <div class="card">
              <div class="col-12 pt-3">
                <p style="text-align: center;" class="small mb-0 fw-bold">Check your email for verification</p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

  </section>
</main><!-- End #main -->
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "main.html" %}
{% load static %}

<title>
    {% block title %}
    Login
    {% endblock title %}
</title>


{% block content %}

<main>
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
          <div class="card mb-3">

            <div class="card-body">
              <div class="container">

                {% include 'accounts/logo.html' %}

                <div class="pb-2">
                  <h5 class="card-title text-center pb-0 fs-4" style="color: black;">Sign in</h5>
                </div>

                <form method="POST"  action="" class="row g-3 needs-validation" novalidate>
                  {% csrf_token %}

                  <div class="col-12">
                    {% if messages %}
                      <ul class="messages">
                          {% for message in messages %}
                              <p{% if message.tags %} style="font-size: 10px; color: brown;" class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                          {% endfor %}
                      </ul>
                  {% endif %}
                    <div class="input-group has-validation">
                      <input type="text" id="ip1" name="username" style="background-color: rgb(211, 241, 147);" placeholder="Username" class="form-control" id="yourUsername" required>
                      <div class="invalid-feedback">Please enter your username.</div>
                    </div>
                  </div>

                  <div class="col-12">
                    <input type="password" id="ip1" name="password" style="background-color: rgb(211, 241, 147);" placeholder="Password" class="form-control" id="yourPassword" required>
                    <div class="invalid-feedback">Please enter your password!</div>
                  </div>

                  <div class="col-6">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                      <label style="font-size: 12px;" class="form-check-label" for="rememberMe">Remember me</label>
                    </div>
                  </div>

                  <div class="col-6 mr-2">
                    <div class="form-check">
                      <a style="font-size: 12px;" href="{% url 'accounts:forgot' %}">Forgot password?</a>                       
                    </div>
                  </div>
                  
                  <div class="col-12 pb-5">
                    <button class="btn w-100" id="btn1" style="background-color: rgb(241, 245, 241); color: blue;" type="submit">Login</button>
                  </div>                 
                </form>
              </div>
            </div>

            <div class="card">
              <div class="col-12 pt-3">
                <p style="text-align: center;" class="small mb-0">Don't have an account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

  </section>
</main><!-- End #main -->
{% endblock content %}

accounts/templates/accounts/logo.html
{% load static %}
<div class="pt-2">
    <h6 class="card-title text-center pb-0 fs-4" style="color: black;">MY</h6>
    <h6 class="card-title text-center pb-0 fs-4" style="color: black;">MUK ASSISTANT</h6>
  </div>

  <div class="d-flex justify-content-center">
    <a href="" class="d-flex align-items-center w-auto">
      <img style="height: 100px;" src="{% static 'assets/img/go.png' %}" alt="">
    </a>
  </div>

accounts/templates/accounts/register.html
{% extends "main.html" %}
{% load static %}
<title>
    {% block title %}
      Register
    {% endblock title %}
</title>
{% block content %}
<main>
  <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center">
    <div class="container-fluid">
      <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">  
          <div class="card">
            <div class="card-body">
              <div class="icon mr-0">
                <a href="/"><i class="bx bx-arrow-back" style="font-size: 30px;"></i></a>
              </div>

              <div class="container">
                
                {% include 'accounts/logo.html' %}

                <div class="pb-2">
                  <h5 class="card-title text-center pb-0 fs-4" style="color: black;">Create an Account</h5>
                </div>

                <form method="POST" action="" class="row g-3 needs-validation" novalidate> 
                  {% csrf_token %}

                  {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <p{% if message.tags %} style="font-size: 10px; color: brown;" class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                    </ul>
                  {% endif %}

                  {% for field in form %}

                    {{field}}

                  {% endfor %}
                  
                  <div class="col-12 pt-2 pb-5">
                    <button id="btn1" style="background-color: rgb(241, 245, 241); color: blue;" class="btn btn-primary w-100" type="submit">SUBMIT</button>
                  </div>
                </form>
              </div>
              </div>
              <div class="card">
                <div class="col-12 pt-3">
                  <p style="text-align: center;" class="small mb-0">Already have account? <a href="{% url 'accounts:login' %}">Login</a></p>
                </div>
              </div>
          </div>  
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock content %}

ar/templates/ar/index.html
{% extends "base.html" %}
{% load static %}

<title>
    {% block title %}
        My Assistant
    {% endblock title %}
</title>

{% block content %}

<!-- ======= Header ======= -->
{% include 'header.html' %}
<!-- End Header -->

<style type="text/css">
  #googleMap {
    width: 100%;
    height: 350px;
  }
</style>

<div class="jumbotron">
  <div class="container">
    <div class="container-fluid">
      <div id="googleMap"></div>

      <div id="output"></div>
    </div>

    <form class="form-horizontal">
      <div class="row">
        <div class="col-xl-6 col-sm-4 box">
          <input type="text" id="from" class="input form-control" placeholder="Origin" required>
          <a class="button"><img src="{% static '/assets/img/camera.jpg' %}" class="image"></a>
        </div>
        <div class="col-xl-6 col-sm-4 box mt-4">
          <input type="text" id="to" placeholder="Destination" class="input form-control" name="" required>
        </div>
      </div>
    </form>

    <div class="row mt-4">
      <div class="col-12 d-flex justify-content-center align-items-center">
        <button class="btn btn-primary btn-lg" style="width: 500px"><i style="font-size: 30px;" class="fas fa-directions"></i></button>
      </div>
    </div>
  </div>
</div>

<script>
  function initMap() {
    var myLatLng = { lat: 0.349998, lng: 32.567164398 };
    var mapOptions = {
      center: myLatLng,
      zoom: 7,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    // create map
    var map = new google.maps.Map(
      document.getElementById("googleMap"),
      mapOptions
    );
  }
</script>

<script>
  function loadMapScript() {
    var script = document.createElement("script");
    script.src =
      "https://maps.googleapis.com/maps/api/js?key=AIzaSyChBSjTjpuifBTsqGopU6jn3ktzxzbluyo&callback=initMap";
    script.async = true;
    script.defer = true;
    document.body.appendChild(script);
  }

  // Call the function to load the map script
  loadMapScript();
</script>


<!-- Include the Maps JavaScript API with its API key -->

<!-- Include the Places API with its API key -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-jd7oyostm5SS8JCzcQpHqNBTv9rszjI&libraries=places"></script>

<!-- Include the Directions API with its API key -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAEk6BCW_-umgHnqlIZ-bikTpF1D9CMVy8"></script>

<!-- Include the Distance Matrix API with its API key -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBJ-J2N1HGVCiBXOA4UoFTRPHPyzy_x5lo"></script>

<!-- Include the Geocoding API with its API key -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAN_aSMYWcLneYoxFT0SftMymjnCxczErA"></script>

</body>
</html>
{% endblock content %}

chatbot/templates/chatbot/chat.html
{% extends "base.html" %}
{% load static %}

<title>
    {% block title %}
    Asking help
    {% endblock title %}
</title>

 {% block content %}

  <!-- ======= Header ======= -->
  {% include 'header.html' %}
 <!-- end of block -->
<br><br>
<div class="container-fluid pt-5">
  <div class="card flex-grow-1">
    <div class="card-body bg-success messages-box pt-5">
      <ul class="list-unstyled messages-list">
        {% for chat in chats %}
          {% if chat.user == request.user %}
            <li class="message sent">
              <div class="message-text">
                <div class="message-sender">
                  <b>User</b>
                </div>
                <div class="message-content">
                  {{chat.message}}
                </div>
              </div>
            </li>
            
            <li class="message received">
              <div class="message-text">
                <div class="message-sender">
                  <b>Lacky</b>
                </div>
                <div class="message-content">
                  {{chat.response}}
                </div>
              </div>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>
  
  <form class="message-form fixed-bottom d-flex justify-content-center mb-5">
    {% csrf_token %}
    <div class="input-group" style="width: 80%;">
      <input type="text" class="form-control message-input" placeholder="Type your message...">
      <div class="input-group-append">
        <button type="submit" class="btn btn-primary btn-send">Send</button>
      </div>
    </div>
  </form>
</div>



 <!-- Add Font Awesome JS script if not already added -->
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  
  <!-- {% include 'footer.html' %} -->

<script>
  const messagesList = document.querySelector('.messages-list');
  const messageForm = document.querySelector('.message-form');
  const messageInput = document.querySelector('.message-input');

  messageForm.addEventListener('submit', (event) => {
    event.preventDefault();

    const message = messageInput.value.trim();
    if (message.length === 0) {
      return;
    }

    const messageItem = document.createElement('li');
    messageItem.classList.add('message', 'sent');
    messageItem.innerHTML = `
        <div class="message-text">
            <div class="message-sender">
                <b>You</b>
            </div>
            <div class="message-content">
                ${message}
            </div>
        </div>`;
    messagesList.appendChild(messageItem);

    messageInput.value = '';

    fetch('/chatbot/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        'csrfmiddlewaretoken': document.querySelector('[name=csrfmiddlewaretoken]').value,
        'message': message
      })
    })
      .then(response => response.json())
      .then(data => {
        const response = data.response;
        const messageItem = document.createElement('li');
        messageItem.classList.add('message', 'received');
        messageItem.innerHTML = `
        <div class="message-text">
            <div class="message-sender">
              <b>AI Chatbot</b>
            </div>
            <div class="message-content">
                ${response}
            </div>
        </div>
          `;
        messagesList.appendChild(messageItem);
      });
  });

</script>

 {% endblock content %}

chatbot/templates/chatbot/index.html
{% extends "base.html" %}
{% load static %}

<title>
    {% block title %}
    Asking help
    {% endblock title %}
</title>

 {% block content %}

  <!-- ======= Header ======= -->
  {% include 'header.html' %}
 <!-- end of block --><br><br><br>

<div style="background-image: url('{% static 'assets/img/backgroun.jpg' %}');">
  <div class="profile-area">
     <div class="container">
       <div class="row">
        <div class="col-md-6">
          <div class="card">
            <div class="img2"><img src="{% static 'assets/img/go.png' %}" alt=""> </div>
              <div class="main-text pt-5">
              <h2>Chat Bot</h2>
              <p>the descrition od the whole thing goes here withb not eve a sing doubt aobiut whats going on ovt the same issued which the fools where talking about. hopw you really get the point claeat and rght bescause it really next to impossible regards this issue. jus know that kabraza</p>
            </div>        
          </div>
         </div>

         <div class="col-md-6">
          <div class="card">
            <div class="img2"><img src="{% static 'assets/img/go.png' %}" alt=""> </div>
              <div class="main-text pt-5">
              <h2>Chat Bot</h2>
              <p>the descrition od the whole thing goes here withb not eve a sing doubt aobiut whats going on ovt the same issued which the fools where talking about. hopw you really get the point claeat and rght bescause it really next to impossible regards this issue. jus know that kabraza</p>
            </div>        
          </div>
         </div>
      </div>
     </div>
   </div>

   <!-- Add Font Awesome JS script if not already added -->
</div>
<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
  
  <!-- {% include 'footer.html' %} -->

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}

        {% endblock title %}
    </title>

    <meta content="" name="description">
    <meta content="" name="keywords">
  
    <!-- Favicons -->
    <link href="{% static 'assets/img/go.png' %}" rel="icon">
    <link href="{% static 'assets/img/go.png' %}" rel="apple-touch-icon">
  
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/ab2155e76b.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <!-- landing page -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css"> 

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- end of landinf pages -->

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">
  
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/ar.css' %}" rel="stylesheet">

   
</head>
<body>

    {% block content %}

    {% endblock content %}


    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.min.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
  
    <!-- Template Main JS File -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- ===========linda code above============= -->

   <script src="{% static 'assets/js/main.js' %}"></script>
   <script src="{% static 'assets/js/app.js' %}"></script>

</body>
<script>
    let input = document.querySelector('.input');
    let button = document.querySelector('.button');
    let image = document.querySelector('.image');

    // Function to update the image and button visibility
    function updateImageVisibility() {
        if (input.value !== '') {
            image.style.width = '0px';
            image.style.height = '0px';
            image.style.opacity = '0';
            image.style.pointerEvents = 'none';

            button.style.opacity = '0';
            button.style.pointerEvents = 'none';
        } else {
            image.style.width = '30px';
            image.style.height = '30px';
            image.style.opacity = '1';
            image.style.pointerEvents = 'auto';

            button.style.opacity = '1';
            button.style.pointerEvents = 'auto';
        }
    }

    // Trigger the function on input change
    input.addEventListener('input', updateImageVisibility);

    // Initial call to set the image visibility
    updateImageVisibility();
</script>
</html>

templates/footer.html
<div class="section">
    <footer  class="footer">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Assistant</span></strong>. All Rights Reserved
              </div>
              <div class="credits">
                Designed by <a href="">Linda Kellen</a>
              </div>
        </div>
    </footer>
</div>

templates/header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/go.png' %}" alt="">
      </a>
    </div>

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item dropdown pe-3">
          {% if request.user.is_authenticated %}
           <li><a class="mr-5" style="font-size: 12px;" href="{% url 'chatbot:home' %}">Hy, {{request.user}}</a></li>
          {% endif %}
          <li><a class="mr-2" href="{% url 'chatbot:home' %}"><i style="font-size: 20px; color: black;" class="ri-home-7-fill"></i></a></li>
          <li><a href="{% url 'ar:home' %}"><i style="font-size: 20px; color: rgb(241, 110, 110);" class="ri-map-pin-2-fill"></i></a></li>
          <a class="nav-link nav-profile d-flex align-items-center mr-2 pe-0" href="#" data-bs-toggle="dropdown">
            <i style="font-size: 30px;" class="bi bi-list"></i>
          </a>

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            
            <li>
              <a class="dropdown-item d-flex align-items-center" href="">
                <i class="bi bi-person"></i>
                <span>profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul>
        </li>
      </ul>
    </nav>
  </header>